# Generated by Django 3.2 on 2021-06-04 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210602_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedtime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 16, 39, 17, 122841)),
        ),
    ]
